#ifndef CONFIG_USERSPACE_H
#define CONFIG_USERSPACE_H

#define TAPPING_TERM 200

#undef COMBO_COUNT
#define COMBO_COUNT 12
#define COMBO_TERM 30

#define FORCE_NKRO

// Filesize reduction
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_BREATHING

#define NO_ACTION_ONESHOT

#endif